#
# Problem: 12
# Question: The sequence of triangle numbers is generated by adding the natural numbers. 
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
# The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?
#
# Answer: ??


import PrimeUtils
import Combo 

primes = PrimeUtils.sieve(1e8)

N = 500
i = 300
while True:
	cur_num = sum(xrange(i+1))
	facts = PrimeUtils.factors(cur_num, primes)
	facts_n = len(facts)
	
	facts_u = set(facts)
	facts_un = len(facts_u)
	
	divs_n = facts_n - facts_un
	for x in xrange(facts_un):
		divs_n = divs_n + Combo.nchoosek(facts_un, x)
	
	# account for divs: [1,num]
	divs_n = divs_n + 2
	
	print "{0} : {1}".format(cur_num, divs_n)
	
	#break
	if divs_n > N:
		print cur_num
		break

	i = i + 1

